# Generated by Django 4.0.3 on 2023-03-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='value',
            new_name='rate',
        ),
    ]
