# Generated by Django 4.0.3 on 2023-03-12 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image_caption_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='book_cover',
            field=models.CharField(choices=[('BIA_CUNG', 'Bìa cứng'), ('BIA_MEM', 'Bìa mềm')], default='Bìa mềm', max_length=100, verbose_name='Status of the category'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
